version: "3.8"
services:
  app:
    container_name: hillel-app
    build:
      context: ./docker/app
      dockerfile: Dockerfile
      args:
        DOCKER_APP_DIR: '${DOCKER_APP_DIR:-/app}'
        XDEBUG_MODE: '${XDEBUG_MODE:-off}'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${DOCKER_APP_PORT}:8081'
    volumes:
      - ./:${DOCKER_APP_DIR}
    environment:
      DOCKER_APP_DIR: '${DOCKER_APP_DIR:-/app}'
      XDEBUG_MODE: '${XDEBUG_MODE:-off}'
      XDEBUG_START_WITH_REQUEST: '${XDEBUG_START_WITH_REQUEST:-yes}'
      XDEBUG_CLIENT_HOST: '${XDEBUG_CLIENT_HOST:-host.docker.internal}'
      XDEBUG_CLIENT_PORT: '${XDEBUG_CLIENT_PORT:-9001}'
      XDEBUG_CLIENT_IDEKEY: '${XDEBUG_CLIENT_IDEKEY:-PHPSTORM}'
      XDEBUG_MAX_NESTING_LEVEL: '${XDEBUG_MAX_NESTING_LEVEL:-1000}'
      PHP_IDE_CONFIG: '${PHP_IDE_CONFIG:-serverName=app}'

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: php-nginx
    ports:
      - '${DOCKER_WEB_PORT:-8080}:80'
    volumes:
      - ./:/app
    networks:
      - app-network

  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '${DOCKER_DB_PORT:-13306}:3306'
    volumes:
      - ./docker/db/entrypoint.d:/docker-entrypoint-initdb.d
      - ./docker/db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD:-password}'
      MYSQL_DATABASE: '${MYSQL_DATABASE:-database}'
      MYSQL_USER: '${MYSQL_USER:-user}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD:-password}'

networks:
  app-network:
    driver: bridge